/**
 * Generates the table section of INVENTORY.md from the resolved content, so
 * the document cannot drift from what the pipeline actually produced.
 */

import { readFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { DUA_SEEDS } from "../content/duas.js";
import { PROPHETS } from "../content/prophets.js";
import { THEMES } from "../content/themes.js";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

type Resolved = {
  id: string;
  ref: string;
  wordCount: number;
  isExcerpt: boolean;
  surahNameEn: string;
};

const resolved: Resolved[] = JSON.parse(
  await readFile(resolve(ROOT, "content/generated/arabic.json"), "utf8"),
);
const byId = new Map(resolved.map((r) => [r.id, r]));
const speakerName = new Map(PROPHETS.map((p) => [p.id, p.name.en]));
const migration = JSON.parse(
  await readFile(resolve(ROOT, "content/generated/legacy-migration.json"), "utf8"),
) as { migrated: { id: string }[]; orphaned: unknown[] };
const migratedIds = new Set(migration.migrated.map((m) => m.id));

const lines: string[] = [];

lines.push(`| # | Duʿāʾ | Speaker | Reference | Words | Excerpt | Themes | TR carried |`);
lines.push(`|---:|---|---|---|---:|:---:|---|:---:|`);

let n = 0;
for (const p of [...PROPHETS].sort((x, y) => x.order - y.order)) {
  const seeds = DUA_SEEDS.filter((s) => s.speaker === p.id);
  for (const s of seeds) {
    const r = byId.get(s.id);
    if (!r) continue;
    n++;
    lines.push(
      `| ${n} | ${s.title.en} | ${speakerName.get(s.speaker) ?? s.speaker} | ${r.ref} ${r.surahNameEn} | ${r.wordCount} | ${r.isExcerpt ? "✓" : "—"} | ${s.themes.join(", ")} | ${migratedIds.has(s.id) ? "✓" : "new"} |`,
    );
  }
}

const excerpts = resolved.filter((r) => r.isExcerpt).length;
const bySpeaker = new Map<string, number>();
for (const s of DUA_SEEDS) bySpeaker.set(s.speaker, (bySpeaker.get(s.speaker) ?? 0) + 1);

console.log(`<!-- generated by scripts/build-inventory.ts — do not edit by hand -->`);
console.log();
console.log(`**${resolved.length} duʿāʾ · ${PROPHETS.filter((p) => p.section === "prophet").length} prophets · ${PROPHETS.filter((p) => p.section === "companion").length} companion-section figures · ${THEMES.length} themes**`);
console.log();
console.log(`${excerpts} are excerpts from a longer āyah (boundary recorded and disclosed); ${resolved.length - excerpts} are whole passages.`);
console.log(`${migratedIds.size} carry Turkish forward from the legacy corpus; ${resolved.length - migratedIds.size} are new and need Turkish written.`);
console.log();
console.log(lines.join("\n"));
console.log();
console.log(`### Per speaker`);
console.log();
console.log(`| Speaker | Section | Duʿāʾ |`);
console.log(`|---|---|---:|`);
for (const p of [...PROPHETS].sort((x, y) => x.order - y.order)) {
  console.log(`| ${p.name.en} | ${p.section} | ${bySpeaker.get(p.id) ?? 0} |`);
}
