/**
 * Generates the table section of INVENTORY.md from the *built* content, so the
 * document cannot drift from what actually ships.
 *
 * Reads content/generated/site.json rather than the seed files — that file is
 * the schema-validated result, and counting seeds instead was how the previous
 * version came to report "27 need Turkish written" after every entry had it.
 */

import { readFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import type { Dua, Prophet, Theme } from "../content/schema.js";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const site = JSON.parse(
  await readFile(resolve(ROOT, "content/generated/site.json"), "utf8"),
) as { duas: Dua[]; prophets: Prophet[]; themes: Theme[] };

const { duas, prophets, themes } = site;
const nameOf = new Map(prophets.map((p) => [p.id, p.name.en]));

const ref = (d: Dua): string => {
  if (d.source.type === "hadith") return `${d.source.collection} ${d.source.number}`;
  if (d.source.type === "attributed") return d.source.locus;
  const a = d.source.ayat;
  return a.length > 1
    ? `${a[0].surah}:${a[0].ayah}–${a[a.length - 1].ayah}`
    : `${a[0].surah}:${a[0].ayah}`;
};

const langs = (d: Dua) => {
  const set = new Set(d.translations.map((t) => t.lang));
  return [...set].sort().join("+");
};

const kind = (d: Dua) =>
  d.source.type === "quran" ? "Qurʾān" : d.source.type === "hadith" ? "Ḥadīth" : "Attributed";

const lines: string[] = [];
lines.push(`| # | Duʿāʾ | Speaker | Reference | Kind | Excerpt | Translations | Themes |`);
lines.push(`|---:|---|---|---|---|:---:|---|---|`);

let n = 0;
for (const p of [...prophets].sort((a, b) => a.order - b.order)) {
  for (const d of duas.filter((x) => x.speaker === p.id)) {
    n++;
    const isExcerpt = d.source.type === "quran" && d.source.excerpt ? "✓" : "—";
    lines.push(
      `| ${n} | ${d.title.en} | ${nameOf.get(d.speaker) ?? d.speaker} | ${ref(d)} | ${kind(d)} | ${isExcerpt} | ${langs(d)} | ${d.themes.join(", ")} |`,
    );
  }
}

const excerpts = duas.filter((d) => d.source.type === "quran" && d.source.excerpt).length;
const withEn = duas.filter((d) => d.translations.some((t) => t.lang === "en")).length;
const withTr = duas.filter((d) => d.translations.some((t) => t.lang === "tr")).length;
const byKind = duas.reduce<Record<string, number>>((acc, d) => {
  acc[kind(d)] = (acc[kind(d)] ?? 0) + 1;
  return acc;
}, {});

console.log(`<!-- generated by scripts/build-inventory.ts — do not edit by hand -->`);
console.log();
console.log(
  `**${duas.length} duʿāʾ · ${prophets.filter((p) => p.section === "prophet").length} prophets · ` +
    `${prophets.filter((p) => p.section === "companion").length} companion-section figures · ${themes.length} themes**`,
);
console.log();
console.log(
  `By source: ${Object.entries(byKind).map(([k, v]) => `${v} ${k}`).join(" · ")}. ` +
    `${excerpts} are excerpts within a longer āyah, each with its boundary recorded and disclosed.`,
);
console.log();
console.log(`Translations: **${withEn}/${duas.length} English, ${withTr}/${duas.length} Turkish.**`);
console.log();
console.log(lines.join("\n"));
console.log();
console.log(`### Per speaker`);
console.log();
console.log(`| Speaker | Section | Duʿāʾ |`);
console.log(`|---|---|---:|`);
for (const p of [...prophets].sort((a, b) => a.order - b.order)) {
  console.log(
    `| ${p.name.en} | ${p.section} | ${duas.filter((d) => d.speaker === p.id).length} |`,
  );
}
