/**
 * Generates the service worker's precache manifest after the site is built.
 *
 * Caching only what a reader happens to visit is not the same as working
 * offline — it means the pages they did not think to open first are the ones
 * missing when they need them. The whole site is 104 static pages and a few
 * fonts, so it is precached outright: someone on a plane, in a hospital, or
 * with no signal gets the entire reference, not the three pages they browsed
 * before the connection dropped.
 */

import { readdir, readFile, writeFile, stat } from "node:fs/promises";
import { join, relative, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DIST = resolve(ROOT, "dist");
const BASE = "/dua";

async function walk(dir: string): Promise<string[]> {
  const out: string[] = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else out.push(full);
  }
  return out;
}

const files = await walk(DIST);
const urls = files
  .map((f) => "/" + relative(DIST, f).split("\\").join("/"))
  // The service worker must not try to cache itself.
  .filter((u) => u !== "/sw.js")
  .map((u) => (u.endsWith("/index.html") ? u.slice(0, -"index.html".length) : u))
  .map((u) => BASE + u)
  .sort();

let bytes = 0;
for (const f of files) bytes += (await stat(f)).size;

const sw = `/*
 * Offline support. Generated by scripts/build-sw.ts — do not edit by hand.
 *
 * The content is static and small, so the entire site is precached on install
 * and served cache-first. Caching only visited pages would mean the entry
 * someone needs is the one they did not happen to open while online.
 */
const VERSION = ${JSON.stringify("dua-" + Date.now().toString(36))};
const PRECACHE = ${JSON.stringify(urls, null, 2)};

self.addEventListener("install", (e) => {
  self.skipWaiting();
  e.waitUntil(
    caches.open(VERSION).then((c) =>
      // Individually, so one 404 cannot fail the whole install.
      Promise.all(PRECACHE.map((u) => c.add(u).catch(() => {}))),
    ),
  );
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (e) => {
  const { request } = e;
  if (request.method !== "GET") return;
  if (new URL(request.url).origin !== location.origin) return;

  e.respondWith(
    caches.match(request, { ignoreSearch: true }).then((hit) => {
      if (hit) {
        // Refresh in the background so a redeploy is picked up next visit.
        fetch(request)
          .then((res) => {
            if (res.ok) caches.open(VERSION).then((c) => c.put(request, res.clone()));
          })
          .catch(() => {});
        return hit;
      }
      return fetch(request)
        .then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(VERSION).then((c) => c.put(request, copy));
          }
          return res;
        })
        .catch(() => caches.match(${JSON.stringify(BASE + "/")}));
    }),
  );
});
`;

await writeFile(resolve(DIST, "sw.js"), sw);
console.error(
  `✓ sw.js precaches ${urls.length} files (${(bytes / 1024 / 1024).toFixed(1)} MB)`,
);
